# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_post_like_add_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_add_count',
            new_name='upvote_count',
        ),
    ]
