# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20171203_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='post',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvote_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_score',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
