# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20171203_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'female'), ('Male', 'male'), ('Both', 'both'), ('None', 'non-specified')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
