# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171129_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='photo',
        ),
    ]
