# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171201_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like_add_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
